variables:
  Email: tahirbaboci96@gmail.com
  Service name: weather-lambda
  Team slack channel: template-slack-channel
  FiZZ build agent: build-docker
  FiZZ build agent role: arn:aws:iam::544725753551:role/jenkins-slave-build
  Usecase: template-usecase
  Team name: i-ntothenetwork
  Vertical: template-vertical
  FiZZ deploy agent: deploy-as24prod
  Segment: template-segment
  Service short description: Lambda to get weather data
features:
- scala:
    description: Basic template to kickstart all Scala projects
- scala.lambda:
    description: Basic template to kickstart Lambdas with Scala
- scala.logging.logback-logstash:
    description: Structured logging
